### ISSUE TITLE
Missing Character \

### ISSUE THREAD

**Issue by MKleinSB** [1010Technologies/pxt-makerbit-lcd1602#1]
Sorry, it´s me again.
It would be funny to display a turning wheel to show the motor is turning right or left.
![Unbenannt](https://user-images.githubusercontent.com/37311672/56848419-0ca02000-68e9-11e9-87a8-da5549bff7f3.png)
But the Character \ is missing in the charset of the LCD-Display. Do you have a solution?

**Comment by philipphenkel** [comment]
@MKleinSB Great idea :-) Unfortunately, the backslash is indeed missing in the default character set. What about a blinking **`>`**?

**Comment by MKleinSB** [comment]
Hm, should work, but my Idea was better ;-)
Is it possible to define an Array of Pixels to be sent to a specified Cursor Position? But only if you have time. Your Package works great!

**Comment by philipphenkel** [comment]
No, we cannot send pixels directly. Fortunately, it might be possible to install some custom characters. This would be an indirect way to address pixels and/or solve your challenge.

https://maxpromer.github.io/LCD-Character-Creator/
http://forum.arduino.cc/index.php?topic=19002.0

We don't have it implemented yet.
Besides simple characters, I would love to have graphic elements to visualize a bar (both horizontal and vertical).
@HyperDuino What do you think?

**Comment by HyperDuino** [comment]
I'm always tempted to do the next cool thing because we can and it's neat to have this amazing set of blocks for MakeCode, but we also need to consider where our next efforts are best placed. For example, I would like to see example lessons, tutorials, etc. on the MakeCode main page. but then again, if I got an email that said the custom character block got made one evening for fun, I'm not saying I wouldn't enjoy playing with it. :)

**Comment by philipphenkel** [comment]
cc81524 enables support for custom LCD characters.

**Comment by HyperDuino** [comment]
:)
